export type DocumentPromptKey = 'memoria' | 'cassazione' | 'eccezione' | 'crossExam' | 'strategy' | 'clienteNote';

const STRICT_PRECEDENT_BAN =
  'DIVIETO ASSOLUTO — non citare mai estremi, sezioni, numeri o anni di sentenze della Cassazione ' +
  'che non siano presenti nel fascicolo o nei materiali caricati. ' +
  'Se un precedente sarebbe utile ma non è verificato: descrivi il principio giuridico e la norma ' +
  'di riferimento senza inventare estremi; scrivi "orientamento giurisprudenziale da ricercare in banca dati". ' +
  'Qualsiasi citazione con numero o anno non proveniente dal fascicolo va marcata DA VERIFICARE prima del deposito.';

import { CASSAZIONE_GUIDE } from './cassazioneGuide';

export const DOC_PROMPTS: Record<DocumentPromptKey, (ctx: string) => string> = {
  memoria: ctx => `${ctx}\n\n---\nRedigi una memoria difensiva completa per questo caso. Struttura l'atto secondo il formato italiano standard:\n\n**INTESTAZIONE** (Tribunale competente, numero procedimento, imputato, difensore)\n**IN FATTO** — narrazione precisa dei fatti rilevanti per la difesa\n**IN DIRITTO** — motivi giuridici articolati, con:\n  - Citazioni normative specifiche (art. X c.p. / art. X c.p.p.)\n  - Precedenti della Cassazione Penale verificati o marcati DA VERIFICARE\n  - Interpretazioni dottrinali rilevanti\n**CONCLUSIONI** — richieste formali al giudice\n\n${STRICT_PRECEDENT_BAN}\n\nScrivi in italiano giuridico formale. Sii specifico e approfondito, non generico.`,

  cassazione: ctx => `${ctx}\n\n---\n${CASSAZIONE_GUIDE}\n\nSulla base del fascicolo sopra e delle istruzioni operative qui indicate, redigi un ricorso per Cassazione completo. Identifica i motivi ex art. 606 c.p.p. più solidi emergenti dai fatti del caso e sviluppa ciascuno con argomentazione tecnica piena, citando i passi esatti della sentenza impugnata. Rispetta rigorosamente la struttura obbligatoria e il principio di autosufficienza. Segnala esplicitamente eventuali dati mancanti nel fascicolo (numero sentenza, data deposito motivazioni, composizione collegio) che il difensore dovrà integrare prima del deposito.\n\n${STRICT_PRECEDENT_BAN}`,

  eccezione: ctx => `${ctx}\n\n---\nRedigi un'eccezione procedurale formale da depositare in udienza, focalizzata sul vizio processuale più solido del fascicolo. Struttura:\n\n**TITOLO ECCEZIONE**\n**NORMA VIOLATA** (articolo preciso del c.p.p. o legge speciale)\n**IN FATTO** — descrizione della violazione procedurale concreta\n**IN DIRITTO** — argomentazione giuridica con:\n  - Interpretazione della norma violata\n  - Conseguenza processuale (nullità / inutilizzabilità / inammissibilità)\n  - Giurisprudenza della Cassazione verificata o da verificare in banca dati\n**RICHIESTA** — provvedimento chiesto al giudice\n\n${STRICT_PRECEDENT_BAN}\n\nSii preciso: indica se si tratta di nullità assoluta, relativa, o inutilizzabilità patologica/fisiologica.`,

  crossExam: ctx => `${ctx}\n\n---\nPreparazione per il controesame dei testimoni dell'accusa. Per ciascun testimone nel fascicolo, sviluppa:\n\n**[NOME TESTIMONE — ruolo]**\nCredibilità: [score]\n\n*Obiettivo del controesame*: [minare la credibilità / estrarre ammissioni favorevoli / limitare il danno]\n\n*Sequenza di domande*:\n1. [domanda di apertura — fatto non contestabile]\n2-5. [sviluppo logico verso la contraddizione o l'ammissione]\nX. [domanda finale incisiva]\n\n*Trappole da evitare*:\n*Documenti da usare come confronto*:\n\nUsa la tecnica del controesame a domande chiuse (sì/no).\n\n${STRICT_PRECEDENT_BAN}`,

  strategy: ctx => `${ctx}\n\n---\nAnalisi strategica approfondita del caso. Valuta ogni linea difensiva con occhio critico da avvocato esperto:\n\nPer ogni strategia:\n- **Probabilità di successo** (realistica, non ottimistica)\n- **Prove necessarie ancora da acquisire**\n- **Rischi e controindicazioni**\n- **Giurisprudenza favorevole** verificata oppure DA VERIFICARE / da ricercare in banca dati\n- **Tempistica tattica** — quando e come giocare questa carta\n\n${STRICT_PRECEDENT_BAN}\n\nConcludi con una **raccomandazione tattica generale**: quale combinazione di strategie adottare, in quale ordine, e quale eventuale piano B prepararsi.`,

  clienteNote: ctx => `${ctx}\n\n---\nIl cliente vuole capire la sua situazione. Prepara una spiegazione in linguaggio semplice e chiaro — senza tecnicismi legali — che risponda a queste domande:\n\n1. **Di cosa è accusato, in parole semplici?**\n2. **Quali sono i rischi concreti (pena, misure cautelari)?**\n3. **Cosa stiamo facendo per difenderlo?**\n4. **Cosa deve fare lui nei prossimi giorni?**\n5. **Cosa NON deve assolutamente fare o dire?**\n\nTono: diretto, rassicurante ma onesto. Evita ogni burocratese. Il cliente deve uscire dal colloquio capendo la situazione senza farsi prendere dal panico.\n\nNota: non citare sentenze o riferimenti giurisprudenziali specifici in questo documento — usa solo linguaggio accessibile al cliente non-giurista. Non inventare precedenti.`,
};
